apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 512Mi
      name: instance1
      replicas: 1
  users:
    - databases:
        - hippo
      name: hippo
      options: SUPERUSER
  postgresVersion: 17
  postGISVersion: '3.4'
  shutdown: false