# To deploy
# 1. Replace the two instances of <NAMESPACE> with the namespace you are deploying this too (ie abc123-dev)
# 2. In OpenShift go to the namespace and click the + in the top bar to add a YAML file. Copy and paste this entire file and click create.
# 3. Run the Github action to deploy the image to the ImageStream which should automatically cause the app to start.

kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: dbvalidation
  labels:
    app: dbvalidation
spec:
  lookupPolicy:
    local: false

---

kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"dbvalidation:latest","namespace":"<NAMESPACE>"},"fieldPath":"spec.template.spec.containers[?(@.name==\"container\")].image","pause":"false"}]'
  name: dbvalidation
  labels:
    app: dbvalidation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbvalidation
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dbvalidation
    spec:
      containers:
        - name: container
          image: 'image-registry.openshift-image-registry.svc:5000/<NAMESPACE>/dbvalidation@latest'
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: USERNAME
              value: username
            - name: PASSWORD
              value: password
          resources:
            requests:
              cpu: 5m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
